# Site settings
title: Trent Milton
email: me@trentmilton.com
description: "This is a place to collect my notes on development and anything else I can think of."
baseurl: ""
url: "https://www.trentmilton.com"
github_username: trentmilton
disqus_shortname: trentmilton-blog

# I'm not sure what this is about, I think it's a jekyll property
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'README.md', 'deploy.sh']

plugins:
  - jekyll-feed

# Outputting
permalink: none

# Tipue search settings
tipue_search:
    include:
    pages: true
    exclude:
    files: [search.html]

# Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"