# Site settings
title: Trent Milton
email: me@trentmilton.com
email_alt: trent@shaydesdsgn.com
description: "A place to collect my notes on development and anything else I can think of."
baseurl: ""
url: "http://trentmilton.com"
github_username: trentmilton
github_username_alt: shaydesdsgn
disqus_shortname: trentmilton-blog

# Build settings
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'README.md', 'deploy.sh']
markdown: kramdown
permalink: none

# Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"